AllCops:
  Include:
    - "**/Rakefile"
    - "**/config.ru"
  Exclude:
    - "db/**/*"
    - "config/**/*"
    - "script/**/*"
    - "bin/**/*"
    - "vendor/**/*"
    - "node_modules/**/*"
    - "spec/factories.rb"
  TargetRubyVersion: 2.2

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Layout/DotPosition:
  EnforcedStyle: trailing

Layout/ExtraSpacing:
  Exclude:
    - "webtrap.gemspec"

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/SpaceAroundOperators:
  Exclude:
    - "webtrap.gemspec"

Metrics/BlockLength:
  Exclude:
    - "webtrap.gemspec"

Metrics/LineLength:
  Enabled: false

Naming/FileName:
  Exclude:
    - "Gemfile"

Naming/PredicateName:
  NamePrefixBlacklist:
    - is_
    - have_

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/NumericLiterals:
  Enabled: false

Style/SingleLineBlockParams:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma

Style/FrozenStringLiteralComment:
  Enabled: false
