language: ruby
sudo: false
cache:
  directories:
    - ../bundle
bundler_args: "--standalone --path ../bundle"
rvm:
  - 2.0.0
  - 2.1
  - 2.2.5
  - 2.3.3
  - 2.4.0
  - ruby-head
before_install: gem install bundler -v 1.13.6
script:
  - bundle exec cucumber
